.nh
.TH "GH-AUTH" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-auth - Authenticate gh and git with GitHub


.SH SYNOPSIS
.PP
\fBgh auth <command> [flags]\fR


.SH AVAILABLE COMMANDS
.TP
\fBgh-auth-login(1)\fR
Log in to a GitHub account

.TP
\fBgh-auth-logout(1)\fR
Log out of a GitHub account

.TP
\fBgh-auth-refresh(1)\fR
Refresh stored authentication credentials

.TP
\fBgh-auth-setup-git(1)\fR
Setup git with GitHub CLI

.TP
\fBgh-auth-status(1)\fR
View all accounts and authentication status

.TP
\fBgh-auth-switch(1)\fR
Switch active GitHub account

.TP
\fBgh-auth-token(1)\fR
Print the authentication token gh uses for a hostname and account


.SH SEE ALSO
.PP
\fBgh(1)\fR
