.nh
.TH "GH-ALIAS-LIST" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-alias-list - List your aliases


.SH SYNOPSIS
.PP
\fBgh alias list [flags]\fR


.SH DESCRIPTION
.PP
This command prints out all of the aliases gh is configured to use.


.SH SEE ALSO
.PP
\fBgh-alias(1)\fR
