.nh
.TH "GH-ALIAS" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-alias - Create command shortcuts


.SH SYNOPSIS
.PP
\fBgh alias <command> [flags]\fR


.SH DESCRIPTION
.PP
Aliases can be used to make shortcuts for gh commands or to compose multiple commands.

.PP
Run \fBgh help alias set\fR to learn more.


.SH AVAILABLE COMMANDS
.TP
\fBgh-alias-delete(1)\fR
Delete set aliases

.TP
\fBgh-alias-import(1)\fR
Import aliases from a YAML file

.TP
\fBgh-alias-list(1)\fR
List your aliases

.TP
\fBgh-alias-set(1)\fR
Create a shortcut for a gh command


.SH SEE ALSO
.PP
\fBgh(1)\fR
