.nh
.TH "GH-BROWSE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-browse - Open the repository in the browser


.SH SYNOPSIS
.PP
\fBgh browse [<number> | <path> | <commit-SHA>] [flags]\fR


.SH DESCRIPTION
.PP
Open the GitHub repository in the web browser.


.SH OPTIONS
.TP
\fB-b\fR, \fB--branch\fR \fB<string>\fR
Select another branch by passing in the branch name

.TP
\fB-c\fR, \fB--commit\fR \fB<string>\fR
Select another commit by passing in the commit SHA, default is the last commit

.TP
\fB-n\fR, \fB--no-browser\fR
Print destination URL instead of opening the browser

.TP
\fB-p\fR, \fB--projects\fR
Open repository projects

.TP
\fB-r\fR, \fB--releases\fR
Open repository releases

.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format

.TP
\fB-s\fR, \fB--settings\fR
Open repository settings

.TP
\fB-w\fR, \fB--wiki\fR
Open repository wiki


.SH EXAMPLE
.EX
$ gh browse
#=> Open the home page of the current repository

$ gh browse script/
#=> Open the script directory of the current repository

$ gh browse 217
#=> Open issue or pull request 217

$ gh browse 77507cd94ccafcf568f8560cfecde965fcfa63
#=> Open commit page

$ gh browse --settings
#=> Open repository settings

$ gh browse main.go:312
#=> Open main.go at line 312

$ gh browse main.go --branch bug-fix
#=> Open main.go with the repository at head of bug-fix branch

$ gh browse main.go --commit=77507cd94ccafcf568f8560cfecde965fcfa63
#=> Open main.go with the repository at commit 775007cd

.EE


.SH SEE ALSO
.PP
\fBgh(1)\fR
