.nh
.TH "GH-CONFIG-CLEAR-CACHE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-config-clear-cache - Clear the cli cache


.SH SYNOPSIS
.PP
\fBgh config clear-cache [flags]\fR


.SH EXAMPLE
.EX
# Clear the cli cache
$ gh config clear-cache

.EE


.SH SEE ALSO
.PP
\fBgh-config(1)\fR
