.nh
.TH "GH-CODESPACE-STOP" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-stop - Stop a running codespace


.SH SYNOPSIS
.PP
\fBgh codespace stop [flags]\fR


.SH OPTIONS
.TP
\fB-c\fR, \fB--codespace\fR \fB<string>\fR
Name of the codespace

.TP
\fB-o\fR, \fB--org\fR \fB<login>\fR
The login handle of the organization (admin-only)

.TP
\fB-R\fR, \fB--repo\fR \fB<string>\fR
Filter codespace selection by repository name (user/repo)

.TP
\fB--repo-owner\fR \fB<string>\fR
Filter codespace selection by repository owner (username or org)

.TP
\fB-u\fR, \fB--user\fR \fB<username>\fR
The username to stop codespace for (used with --org)


.SH SEE ALSO
.PP
\fBgh-codespace(1)\fR
