.nh
.TH "GH-CONFIG" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-config - Manage configuration for gh


.SH SYNOPSIS
.PP
\fBgh config <command> [flags]\fR


.SH DESCRIPTION
.PP
Display or change configuration settings for gh.

.PP
Current respected settings:
- \fBgit_protocol\fR: the protocol to use for git clone and push operations {https|ssh} (default https)
- \fBeditor\fR: the text editor program to use for authoring text
- \fBprompt\fR: toggle interactive prompting in the terminal {enabled|disabled} (default enabled)
- \fBpager\fR: the terminal pager program to send standard output to
- \fBhttp_unix_socket\fR: the path to a Unix socket through which to make an HTTP connection
- \fBbrowser\fR: the web browser to use for opening URLs


.SH AVAILABLE COMMANDS
.TP
\fBgh-config-clear-cache(1)\fR
Clear the cli cache

.TP
\fBgh-config-get(1)\fR
Print the value of a given configuration key

.TP
\fBgh-config-list(1)\fR
Print a list of configuration keys and values

.TP
\fBgh-config-set(1)\fR
Update configuration with a value for the given key


.SH SEE ALSO
.PP
\fBgh(1)\fR
