.nh
.TH "GH-CODESPACE-LOGS" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-logs - Access codespace logs


.SH SYNOPSIS
.PP
\fBgh codespace logs [flags]\fR


.SH OPTIONS
.TP
\fB-c\fR, \fB--codespace\fR \fB<string>\fR
Name of the codespace

.TP
\fB-f\fR, \fB--follow\fR
Tail and follow the logs

.TP
\fB-R\fR, \fB--repo\fR \fB<string>\fR
Filter codespace selection by repository name (user/repo)

.TP
\fB--repo-owner\fR \fB<string>\fR
Filter codespace selection by repository owner (username or org)


.SH SEE ALSO
.PP
\fBgh-codespace(1)\fR
