.nh
.TH "GH-CACHE-DELETE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-cache-delete - Delete Github Actions caches


.SH SYNOPSIS
.PP
\fBgh cache delete [<cache-id>| <cache-key> | --all] [flags]\fR


.SH DESCRIPTION
.EX
	Delete Github Actions caches.

	Deletion requires authorization with the "repo" scope.
.EE


.SH OPTIONS
.TP
\fB-a\fR, \fB--all\fR
Delete all caches


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXAMPLE
.EX
# Delete a cache by id
$ gh cache delete 1234

# Delete a cache by key
$ gh cache delete cache-key

# Delete a cache by id in a specific repo
$ gh cache delete 1234 --repo cli/cli

# Delete all caches
$ gh cache delete --all

.EE


.SH SEE ALSO
.PP
\fBgh-cache(1)\fR
