.nh
.TH "GH-EXTENSION-UPGRADE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-extension-upgrade - Upgrade installed extensions


.SH SYNOPSIS
.PP
\fBgh extension upgrade {<name> | --all} [flags]\fR


.SH OPTIONS
.TP
\fB--all\fR
Upgrade all extensions

.TP
\fB--dry-run\fR
Only display upgrades

.TP
\fB--force\fR
Force upgrade extension


.SH SEE ALSO
.PP
\fBgh-extension(1)\fR
