.nh
.TH "GH-EXTENSION-INSTALL" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-extension-install - Install a gh extension from a repository


.SH SYNOPSIS
.PP
\fBgh extension install <repository> [flags]\fR


.SH DESCRIPTION
.PP
Install a GitHub repository locally as a GitHub CLI extension.

.PP
The repository argument can be specified in \fBOWNER/REPO\fR format as well as a full URL.
The URL format is useful when the repository is not hosted on github.com.

.PP
To install an extension in development from the current directory, use \fB\&.\fR as the
value of the repository argument.

.PP
For the list of available extensions, see 
\[la]https://github.com/topics/gh\-extension\[ra]\&.


.SH OPTIONS
.TP
\fB--force\fR
force upgrade extension, or ignore if latest already installed

.TP
\fB--pin\fR \fB<string>\fR
pin extension to a release tag or commit ref


.SH EXAMPLE
.EX
$ gh extension install owner/gh-extension
$ gh extension install https://git.example.com/owner/gh-extension
$ gh extension install .

.EE


.SH SEE ALSO
.PP
\fBgh-extension(1)\fR
