.nh
.TH "GH-GIST-EDIT" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gist-edit - Edit one of your gists


.SH SYNOPSIS
.PP
\fBgh gist edit {<id> | <url>} [<filename>] [flags]\fR


.SH OPTIONS
.TP
\fB-a\fR, \fB--add\fR \fB<string>\fR
Add a new file to the gist

.TP
\fB-d\fR, \fB--desc\fR \fB<string>\fR
New description for the gist

.TP
\fB-f\fR, \fB--filename\fR \fB<string>\fR
Select a file to edit

.TP
\fB-r\fR, \fB--remove\fR \fB<string>\fR
Remove a file from the gist


.SH SEE ALSO
.PP
\fBgh-gist(1)\fR
