.nh
.TH "GH-GIST-LIST" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gist-list - List your gists


.SH SYNOPSIS
.PP
\fBgh gist list [flags]\fR


.SH OPTIONS
.TP
\fB-L\fR, \fB--limit\fR \fB<int> (default 10)\fR
Maximum number of gists to fetch

.TP
\fB--public\fR
Show only public gists

.TP
\fB--secret\fR
Show only secret gists


.SH SEE ALSO
.PP
\fBgh-gist(1)\fR
