.nh
.TH "GH-GIST-CLONE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gist-clone - Clone a gist locally


.SH SYNOPSIS
.PP
\fBgh gist clone <gist> [<directory>] [-- <gitflags>...]\fR


.SH DESCRIPTION
.PP
Clone a GitHub gist locally.

.PP
A gist can be supplied as argument in either of the following formats:
- by ID, e.g. \fB5b0e0062eb8e9654adad7bb1d81cc75f\fR
- by URL, e.g. \fBhttps://gist.github.com/OWNER/5b0e0062eb8e9654adad7bb1d81cc75f\fR

.PP
Pass additional \fBgit clone\fR flags by listing them after \fB--\fR\&.


.SH SEE ALSO
.PP
\fBgh-gist(1)\fR
