.nh
.TH "GH-GIST-RENAME" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gist-rename - Rename a file in a gist


.SH SYNOPSIS
.PP
\fBgh gist rename {<id> | <url>} <oldFilename> <newFilename> [flags]\fR


.SH DESCRIPTION
.PP
Rename a file in the given gist ID / URL.


.SH SEE ALSO
.PP
\fBgh-gist(1)\fR
