.nh
.TH "GH-GIST-VIEW" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gist-view - View a gist


.SH SYNOPSIS
.PP
\fBgh gist view [<id> | <url>] [flags]\fR


.SH DESCRIPTION
.PP
View the given gist or select from recent gists.


.SH OPTIONS
.TP
\fB-f\fR, \fB--filename\fR \fB<string>\fR
Display a single file from the gist

.TP
\fB--files\fR
List file names from the gist

.TP
\fB-r\fR, \fB--raw\fR
Print raw instead of rendered gist contents

.TP
\fB-w\fR, \fB--web\fR
Open gist in the browser


.SH SEE ALSO
.PP
\fBgh-gist(1)\fR
