.nh
.TH "GH-GIST" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gist - Manage gists


.SH SYNOPSIS
.PP
\fBgh gist <command> [flags]\fR


.SH DESCRIPTION
.PP
Work with GitHub gists.


.SH AVAILABLE COMMANDS
.TP
\fBgh-gist-clone(1)\fR
Clone a gist locally

.TP
\fBgh-gist-create(1)\fR
Create a new gist

.TP
\fBgh-gist-delete(1)\fR
Delete a gist

.TP
\fBgh-gist-edit(1)\fR
Edit one of your gists

.TP
\fBgh-gist-list(1)\fR
List your gists

.TP
\fBgh-gist-rename(1)\fR
Rename a file in a gist

.TP
\fBgh-gist-view(1)\fR
View a gist


.SH SEE ALSO
.PP
\fBgh(1)\fR
