.nh
.TH "GH-GPG-KEY" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gpg-key - Manage GPG keys


.SH SYNOPSIS
.PP
\fBgh gpg-key <command> [flags]\fR


.SH DESCRIPTION
.PP
Manage GPG keys registered with your GitHub account.


.SH AVAILABLE COMMANDS
.TP
\fBgh-gpg-key-add(1)\fR
Add a GPG key to your GitHub account

.TP
\fBgh-gpg-key-delete(1)\fR
Delete a GPG key from your GitHub account

.TP
\fBgh-gpg-key-list(1)\fR
Lists GPG keys in your GitHub account


.SH SEE ALSO
.PP
\fBgh(1)\fR
