.nh
.TH "GH-ISSUE-DELETE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-issue-delete - Delete issue


.SH SYNOPSIS
.PP
\fBgh issue delete {<number> | <url>} [flags]\fR


.SH OPTIONS
.TP
\fB--yes\fR
confirm deletion without prompting


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fBgh-issue(1)\fR
