.nh
.TH "GH-LABEL-CREATE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-label-create - Create a new label


.SH SYNOPSIS
.PP
\fBgh label create <name> [flags]\fR


.SH DESCRIPTION
.PP
Create a new label on GitHub, or update an existing one with \fB--force\fR\&.

.PP
Must specify name for the label. The description and color are optional.
If a color isn't provided, a random one will be chosen.

.PP
The label color needs to be 6 character hex value.


.SH OPTIONS
.TP
\fB-c\fR, \fB--color\fR \fB<string>\fR
Color of the label

.TP
\fB-d\fR, \fB--description\fR \fB<string>\fR
Description of the label

.TP
\fB-f\fR, \fB--force\fR
Update the label color and description if label already exists


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXAMPLE
.EX
# create new bug label
$ gh label create bug --description "Something isn't working" --color E99695

.EE


.SH SEE ALSO
.PP
\fBgh-label(1)\fR
