.nh
.TH "GH-LABEL" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-label - Manage labels


.SH SYNOPSIS
.PP
\fBgh label <command> [flags]\fR


.SH DESCRIPTION
.PP
Work with GitHub labels.


.SH AVAILABLE COMMANDS
.TP
\fBgh-label-clone(1)\fR
Clones labels from one repository to another

.TP
\fBgh-label-create(1)\fR
Create a new label

.TP
\fBgh-label-delete(1)\fR
Delete a label from a repository

.TP
\fBgh-label-edit(1)\fR
Edit a label

.TP
\fBgh-label-list(1)\fR
List labels in a repository


.SH OPTIONS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fBgh(1)\fR
