.nh
.TH "GH-ORG" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-org - Manage organizations


.SH SYNOPSIS
.PP
\fBgh org <command> [flags]\fR


.SH DESCRIPTION
.PP
Work with Github organizations.


.SH GENERAL COMMANDS
.TP
\fBgh-org-list(1)\fR
List organizations for the authenticated user.


.SH EXAMPLE
.EX
$ gh org list

.EE


.SH SEE ALSO
.PP
\fBgh(1)\fR
