.nh
.TH "GH-PR-CLOSE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-pr-close - Close a pull request


.SH SYNOPSIS
.PP
\fBgh pr close {<number> | <url> | <branch>} [flags]\fR


.SH OPTIONS
.TP
\fB-c\fR, \fB--comment\fR \fB<string>\fR
Leave a closing comment

.TP
\fB-d\fR, \fB--delete-branch\fR
Delete the local and remote branch after close


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fBgh-pr(1)\fR
