.nh
.TH "GH-PROJECT-ITEM-LIST" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-project-item-list - List the items in a project


.SH SYNOPSIS
.PP
\fBgh project item-list [<number>] [flags]\fR


.SH OPTIONS
.TP
\fB--format\fR \fB<string>\fR
Output format: {json}

.TP
\fB-q\fR, \fB--jq\fR \fB<expression>\fR
Filter JSON output using a jq expression

.TP
\fB-L\fR, \fB--limit\fR \fB<int> (default 30)\fR
Maximum number of items to fetch

.TP
\fB--owner\fR \fB<string>\fR
Login of the owner. Use "@me" for the current user.

.TP
\fB-t\fR, \fB--template\fR \fB<string>\fR
Format JSON output using a Go template; see "gh help formatting"


.SH EXAMPLE
.EX
# list the items in the current users's project "1"
gh project item-list 1 --owner "@me"

.EE


.SH SEE ALSO
.PP
\fBgh-project(1)\fR
