.nh
.TH "GH-PROJECT-CLOSE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-project-close - Close a project


.SH SYNOPSIS
.PP
\fBgh project close [<number>] [flags]\fR


.SH OPTIONS
.TP
\fB--format\fR \fB<string>\fR
Output format: {json}

.TP
\fB-q\fR, \fB--jq\fR \fB<expression>\fR
Filter JSON output using a jq expression

.TP
\fB--owner\fR \fB<string>\fR
Login of the owner. Use "@me" for the current user.

.TP
\fB-t\fR, \fB--template\fR \fB<string>\fR
Format JSON output using a Go template; see "gh help formatting"

.TP
\fB--undo\fR
Reopen a closed project


.SH EXAMPLE
.EX
# close project "1" owned by monalisa
gh project close 1 --owner monalisa

# reopen closed project "1" owned by github
gh project close 1 --owner github --undo

.EE


.SH SEE ALSO
.PP
\fBgh-project(1)\fR
