.nh
.TH "GH-PR-LOCK" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-pr-lock - Lock pull request conversation


.SH SYNOPSIS
.PP
\fBgh pr lock {<number> | <url>} [flags]\fR


.SH OPTIONS
.TP
\fB-r\fR, \fB--reason\fR \fB<string>\fR
Optional reason for locking conversation (off_topic, resolved, spam, too_heated).


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fBgh-pr(1)\fR
