.nh
.TH "GH-PROJECT-ITEM-ARCHIVE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-project-item-archive - Archive an item in a project


.SH SYNOPSIS
.PP
\fBgh project item-archive [<number>] [flags]\fR


.SH OPTIONS
.TP
\fB--format\fR \fB<string>\fR
Output format: {json}

.TP
\fB--id\fR \fB<string>\fR
ID of the item to archive

.TP
\fB-q\fR, \fB--jq\fR \fB<expression>\fR
Filter JSON output using a jq expression

.TP
\fB--owner\fR \fB<string>\fR
Login of the owner. Use "@me" for the current user.

.TP
\fB-t\fR, \fB--template\fR \fB<string>\fR
Format JSON output using a Go template; see "gh help formatting"

.TP
\fB--undo\fR
Unarchive an item


.SH EXAMPLE
.EX
# archive an item in the current user's project "1"
gh project item-archive 1 --owner "@me" --id <item-ID>

.EE


.SH SEE ALSO
.PP
\fBgh-project(1)\fR
