.nh
.TH "GH-RELEASE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-release - Manage releases


.SH SYNOPSIS
.PP
\fBgh release <command> [flags]\fR


.SH GENERAL COMMANDS
.TP
\fBgh-release-create(1)\fR
Create a new release

.TP
\fBgh-release-list(1)\fR
List releases in a repository


.SH TARGETED COMMANDS
.TP
\fBgh-release-delete(1)\fR
Delete a release

.TP
\fBgh-release-delete-asset(1)\fR
Delete an asset from a release

.TP
\fBgh-release-download(1)\fR
Download release assets

.TP
\fBgh-release-edit(1)\fR
Edit a release

.TP
\fBgh-release-upload(1)\fR
Upload assets to a release

.TP
\fBgh-release-view(1)\fR
View information about a release


.SH OPTIONS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fBgh(1)\fR
