.nh
.TH "GH-REPO-DELETE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo-delete - Delete a repository


.SH SYNOPSIS
.PP
\fBgh repo delete [<repository>] [flags]\fR


.SH DESCRIPTION
.PP
Delete a GitHub repository.

.PP
With no argument, deletes the current repository. Otherwise, deletes the specified repository.

.PP
Deletion requires authorization with the "delete_repo" scope.
To authorize, run "gh auth refresh -s delete_repo"


.SH OPTIONS
.TP
\fB--yes\fR
confirm deletion without prompting


.SH SEE ALSO
.PP
\fBgh-repo(1)\fR
