.nh
.TH "GH-REPO-DEPLOY-KEY-DELETE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo-deploy-key-delete - Delete a deploy key from a GitHub repository


.SH SYNOPSIS
.PP
\fBgh repo deploy-key delete <key-id> [flags]\fR


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fBgh-repo-deploy-key(1)\fR
