.nh
.TH "GH-RUN-CANCEL" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-run-cancel - Cancel a workflow run


.SH SYNOPSIS
.PP
\fBgh run cancel [<run-id>] [flags]\fR


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fBgh-run(1)\fR
