.nh
.TH "GH-REPO-RENAME" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo-rename - Rename a repository


.SH SYNOPSIS
.PP
\fBgh repo rename [<new-name>] [flags]\fR


.SH DESCRIPTION
.PP
Rename a GitHub repository.

.PP
By default, this renames the current repository; otherwise renames the specified repository.


.SH OPTIONS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format

.TP
\fB-y\fR, \fB--yes\fR
Skip the confirmation prompt


.SH SEE ALSO
.PP
\fBgh-repo(1)\fR
