.nh
.TH "GH-REPO" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo - Manage repositories


.SH SYNOPSIS
.PP
\fBgh repo <command> [flags]\fR


.SH DESCRIPTION
.PP
Work with GitHub repositories.


.SH GENERAL COMMANDS
.TP
\fBgh-repo-create(1)\fR
Create a new repository

.TP
\fBgh-repo-list(1)\fR
List repositories owned by user or organization


.SH TARGETED COMMANDS
.TP
\fBgh-repo-archive(1)\fR
Archive a repository

.TP
\fBgh-repo-clone(1)\fR
Clone a repository locally

.TP
\fBgh-repo-delete(1)\fR
Delete a repository

.TP
\fBgh-repo-deploy-key(1)\fR
Manage deploy keys in a repository

.TP
\fBgh-repo-edit(1)\fR
Edit repository settings

.TP
\fBgh-repo-fork(1)\fR
Create a fork of a repository

.TP
\fBgh-repo-rename(1)\fR
Rename a repository

.TP
\fBgh-repo-set-default(1)\fR
Configure default repository for this directory

.TP
\fBgh-repo-sync(1)\fR
Sync a repository

.TP
\fBgh-repo-unarchive(1)\fR
Unarchive a repository

.TP
\fBgh-repo-view(1)\fR
View a repository


.SH EXAMPLE
.EX
$ gh repo create
$ gh repo clone cli/cli
$ gh repo view --web

.EE


.SH SEE ALSO
.PP
\fBgh(1)\fR
