.nh
.TH "GH-SEARCH" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-search - Search for repositories, issues, and pull requests


.SH SYNOPSIS
.PP
\fBgh search <command> [flags]\fR


.SH DESCRIPTION
.PP
Search across all of GitHub.


.SH AVAILABLE COMMANDS
.TP
\fBgh-search-code(1)\fR
Search within code

.TP
\fBgh-search-commits(1)\fR
Search for commits

.TP
\fBgh-search-issues(1)\fR
Search for issues

.TP
\fBgh-search-prs(1)\fR
Search for pull requests

.TP
\fBgh-search-repos(1)\fR
Search for repositories


.SH SEE ALSO
.PP
\fBgh(1)\fR
