.nh
.TH "GH-SSH-KEY-ADD" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-ssh-key-add - Add an SSH key to your GitHub account


.SH SYNOPSIS
.PP
\fBgh ssh-key add [<key-file>] [flags]\fR


.SH OPTIONS
.TP
\fB-t\fR, \fB--title\fR \fB<string>\fR
Title for the new key

.TP
\fB--type\fR \fB<string> (default "authentication")\fR
Type of the ssh key: {authentication|signing}


.SH SEE ALSO
.PP
\fBgh-ssh-key(1)\fR
