.nh
.TH "GH-SSH-KEY-DELETE" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-ssh-key-delete - Delete an SSH key from your GitHub account


.SH SYNOPSIS
.PP
\fBgh ssh-key delete <id> [flags]\fR


.SH OPTIONS
.TP
\fB-y\fR, \fB--yes\fR
Skip the confirmation prompt


.SH SEE ALSO
.PP
\fBgh-ssh-key(1)\fR
