.nh
.TH "GH-WORKFLOW" "1" "Apr 2024" "GitHub CLI 2.48.0" "GitHub CLI manual"

.SH NAME
.PP
gh-workflow - View details about GitHub Actions workflows


.SH SYNOPSIS
.PP
\fBgh workflow <command> [flags]\fR


.SH DESCRIPTION
.PP
List, view, and run workflows in GitHub Actions.


.SH AVAILABLE COMMANDS
.TP
\fBgh-workflow-disable(1)\fR
Disable a workflow

.TP
\fBgh-workflow-enable(1)\fR
Enable a workflow

.TP
\fBgh-workflow-list(1)\fR
List workflows

.TP
\fBgh-workflow-run(1)\fR
Run a workflow by creating a workflow_dispatch event

.TP
\fBgh-workflow-view(1)\fR
View the summary of a workflow


.SH OPTIONS
.TP
\fB-R\fR, \fB--repo\fR \fB<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fBgh(1)\fR
